Add lan channel fact and user channel support
jhoblitt/puppet-ipmi pull request #78
Opened 2024-09-10 16:56 UTC by nathanlcarlson

Based on https://github.com/jhoblitt/puppet-ipmi/pull/32 .

Intentionally named ::user parameter `channel` instead of `lan_channel` to be more general.

2024-09-10 17:27 UTC, jhoblitt commented
@nathanlcarlson How would you feel about adding the channel as a structured fact. Something like `ipmi.channel`?

2024-09-10 18:01 UTC, jhoblitt commented
> @jhoblitt Sure. Just this fact or should I create a structure for all `impi*` facts? The current flat facts could remain and I could add docs about them being deprecated?

I was only hoping to stop the growth of top level facts but if your willing to do the full conversion, that would be fantastic!

2024-09-10 19:01 UTC, nathanlcarlson commented
Kk, I made some standalone gathering and structuring of the facts. I'm not sure how REFERENCE.md gets updated or if there are other PDK items to take care of.

2024-09-10 19:04 UTC, nathanlcarlson commented
Ahh, I found the reference update command in the test results.

2024-09-11 15:35 UTC, nathanlcarlson commented
It looks like these new failures are related to CentOS package mirrors? Maybe partly related to the retirement of CentOS 7?

2024-09-11 16:52 UTC, nathanlcarlson commented
Those may be difficult to resolve. Any chance we can just ignore them?

2024-09-11 17:13 UTC, jhoblitt commented
> Those may be difficult to resolve. Any chance we can just ignore them?

I think we should remove centos completely from `metadata.json` in another PR labeled as a `breaking-change`.  Do you want to take that on too? :pray:

2024-09-11 17:16 UTC, nathanlcarlson commented
I did my best to track down this issue and opened this https://github.com/voxpupuli/beaker-docker/issues/144 and am trying the advice there.

2024-09-11 17:25 UTC, jhoblitt commented
It's the plumbing in those module that needs to be updated.  I'll run msync on it shortly.

2024-09-11 17:34 UTC, jhoblitt commented
FYI:
- #79
- #80 
- #81 
- #82

2024-09-11 17:38 UTC, jhoblitt commented
@nathanlcarlson CI is passing on `master` now.  Could you try a rebase?

2024-09-11 18:50 UTC, jhoblitt requested changes

2024-09-11 18:50 UTC, jhoblitt commented on lib/facter/ipmi.rb
> +    ipmi_hash = {}
This all looks good except I have a quibble with using Hungarian notation.

2024-09-12 15:44 UTC, jhoblitt approved these changes
LGTM. Thank you for doing the fact conversion!

2024-09-12 15:45 UTC, merged

2024-09-12 17:55 UTC, jhoblitt commented
Released as https://github.com/jhoblitt/puppet-ipmi/tree/v6.0.0